# Generated by Django 4.2.4 on 2023-12-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(default='page_media/food.png', upload_to='uploads_restaurants/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(null=True, upload_to='orders_media/'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TimeField(auto_now=True)),
                ('fk_id_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food_system.request')),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='fk_id_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='food_system.history'),
        ),
    ]
