# Generated by Django 4.2.4 on 2023-12-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_system', '0002_alter_business_image_alter_request_file_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRequest',
            fields=[
                ('id_history_request', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='Sin tomar', max_length=30)),
                ('delivery_location', models.CharField(max_length=250)),
                ('desc_delivery', models.CharField(max_length=1000, null=True)),
                ('pick_up_location', models.CharField(default='Pick-up location', max_length=250)),
                ('desc_pick_up_location', models.CharField(max_length=1000, null=True)),
                ('business_name', models.CharField(max_length=70, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_system.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='fk_id_history',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='historyrequest',
            name='fk_id_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_system.request'),
        ),
        migrations.AddField(
            model_name='historyrequest',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
