# Generated by Django 4.2.4 on 2023-12-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_system', '0003_historyrequest_remove_request_fk_id_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrequest',
            name='fk_id_request',
        ),
    ]
