# Generated by Django 4.2.4 on 2023-12-07 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_system', '0004_remove_historyrequest_fk_id_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDelivery',
            fields=[
                ('id_history_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now=True)),
                ('fk_id_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_deliveries_history', to=settings.AUTH_USER_MODEL)),
                ('fk_id_delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_deliveries_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
