# Generated by Django 4.2.4 on 2023-12-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='users_pfp/photoprofile.jpg', null=True, upload_to='users_pfp/'),
        ),
    ]
